server:
  ssl:
    key-store: classpath:springboot.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: springboot
    key-password: password
  port: 8443
#
#https://simulator-api.db.com/gw/oidc/authorize?response_type=code&client_id=ad849f52-124e-485c-88ce-08fc4142ecaa&state=xyz